### ISSUE TITLE
혹시 업데이트 가능할까요...

### ISSUE THREAD

**Issue by nhwook** [ParanScreen/omegat-plugin-navertranslate#1]
OmegaT에서 파파고 쓸 수 있는 방법 엄청 찾다가 찾았는데.. 지금 OmegaT에 적용이 안되는것 같아서요.. 
부탁드립니다!

**Comment by ParanScreen** [comment]
이 Github 계정을 한동안 사용하지 않아서 확인이 많이 늦었습니다....
보니까 네이버에서 몇 년 전에 구 API의 지원을 끊었던 것을 확인했고, 현행 Papago N2MT API를 사용하도록 업데이트가 완료되었습니다. 감사합니다.
