### ISSUE TITLE
NAVER Ncloud 대응 여부

### ISSUE THREAD

**Issue by unicode45** [ParanScreen/omegat-plugin-navertranslate#2]
안녕하세요, 새로 버전업 된 파파고 무료 버전용 잘 쓰고 있습니다.
단, 일일 번역 제한이 있어서 혹시 가능하다면 상용 버전인 NAVER Ncloud의 API에도 대응시켜주실 수 있으실지요?
바쁘시겠지만 검토 부탁드립니다.

**Comment by ParanScreen** [comment]
안녕하세요,

현재로서는 상용API에 대응할 계획이 없습니다.
API 개편 이후 요청가능수가 일 1만에서 5천으로 줄어들은 만큼, 일일 요청 수 제한을 우회할 수 있게 하는 방법 등을 검토 중에 있으나, 구현 일정은 미정인 점 양해부탁드립니다.

감사합니다.

**Comment by unicode45** [comment]
네, 잘 알겠습니다. 답변 감사드립니다!

**Comment by unicode45** [comment]
https://developers.naver.com/notice/article/14501
올해 2월부로 무료 papago가 종료되었네요 ; ;
